### ISSUE TITLE
problème avec la police du theme ggplot dans l'export pdf

### ISSUE THREAD

**Issue by Taborski** [davidcarayon/InraeThemes#2]
Bonjour,
Tout d'abord, merci pour ce repo, ça m'a beacuoup aidé à comprendre et personnaliser mes documents. 

Juste pour faire remonter, je  knit sans problème un Rmd en html, mais en voulant faire une exportation du pdf en plus je me suis rendu compte que le InraeThemes produisait une erreur. En effet la police n'est pas reconnu. 

je m'en suis sorti en changeant les options avec dev = "cairo_pdf". 

bref je ne sais pas si c'est moi qui me suis planté dans l'installation/paramétrisation de mon environnement. 

Un exemple reproducible si jamais: 

---
title: "Untitled"
author: "Tom Taborski"
date: "11/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(InraeThemes)
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
ggplot(pressure, aes(temperature, pressure))+
  geom_line()+
  theme_inrae()
```

**Comment by DDorch** [comment]
Bonjour, 

Je crois que j'ai eu le même problème sous Windows, les polices Raleway et Avenir Next Pro n'étaient pas prises en compte dans les graphiques ggplot pour produire un rapport pagedown.

J'ai ajouté ces deux instructions dans le chunck de setup ce qui a résolu le problème:

```r
windowsFonts("Raleway" = windowsFont("Raleway"))
windowsFonts("Avenir Next Pro" = windowsFont("Avenir Next LT Pro"))
```

**Comment by davidcarayon** [comment]
Bonjour, désolé du retard de la réponse, j'ai n'ai pas reçu de notification pour cette issue.

Merci pour vos retours, je vais implémenter vos suggestions dans la documentation de la prochaine version du package.

D'ailleurs, vos contributions sont tout à fait les bienvenues, l'objectif est que ce package profite à toute notre communauté R-INRAE !
