### ISSUE TITLE
PR#45 has been merged

### ISSUE THREAD

**Issue by holtzy** [davidcarayon/InraeThemes#7]
Hi!

It looks like the PR#45 mentioned in your repo has been merged. It might be helpful to update the doc. I am not sure how the 2 new functions should be used though 🤔

Thanks for your work!

**Comment by davidcarayon** [comment]
Hi !

Thank you for the feedback. The goal of the PR#45 was to provide the `quarto_install()` function through the quarto R package and I was waiting for it to avoid using terminal (some INRAE users are very basic R/Rstudio users and don't really want to use terminal).

It seems the PR has been merged but only for the dev version, I will be waiting for it to be included in the next update to add this possibility in the doc.

BTW, All the quarto related stuff has been moved to my extension, this package is now only about ggplot and bootstrap themes as you can see that I released the V3.0.0 ;)

Thank again for all your feedback !
